# List the start up tasks. Learn more https://www.gitpod.io/docs/config-start-tasks/
tasks:
  - init: > 
      wget https://repo.anaconda.com/miniconda/Miniconda3-py310_22.11.1-1-Linux-x86_64.sh -O /tmp/Minconda3.sh &&
      bash /tmp/Minconda3.sh -b -p /workspace/miniconda3 &&
      echo "export PATH=/workspace/miniconda3/bin:$PATH" >> ~/.bashrc &&
      source ~/.bashrc &&
      conda env create -n parrot_env -f envs_cpu.yaml && 
      /workspace/miniconda3/envs/parrot_env/bin/python preprocess_script/download_data.py

    command: >
      cd /workspace/Parrot/web_app &&
      /workspace/miniconda3/envs/parrot_env/bin/python app.py

# List the ports to expose. Learn more https://www.gitpod.io/docs/config-ports/
ports:
  - port: 8000
    onOpen: open-preview
