model_args:
  evaluate_during_training: true
  fp16: false
  gradient_accumulation_steps: 1
  use_multiprocessing: false
  learning_rate: 2.0e-04
  manual_seed: 42
  max_seq_length: 512
  num_train_epochs: 100
  pretrained_path: ./outputs/best_rcm_model_pretrain
  output_dir: ./out/Parrot_train_in_Reaxy_TotalSyn_Condition
  best_model_dir: ./outputs/Parrot_train_in_Reaxy_TotalSyn_Condition
  overwrite_output_dir: true
  regression: false
  thread_count: 8
  train_batch_size: 8
  wandb_project: Parrot_train_in_Reaxy_TotalSyn_Condition
  warmup_ratio: 0.0
  decoder_args:
    d_model: 256
    dim_feedforward: 256
    dropout: 0.1
    nhead: 4
    num_decoder_layers: 3
    tgt_vocab_size: None

dataset_args:
  use_temperature: true
  dataset_root: ./dataset/source_dataset/Reaxys_total_syn_condition_final
  database_fname: Reaxys_total_syn_condition.csv     # The license of Reaxys is required. It will not be shared here!
 
testset_args:
  testset_distinguish_catalyst: true

